import { Technique } from './types';

type CompactTechnique = [
  id: string, de: string, en: string, ja: string, romaji: string,
  category: string, subcategory: string, position: string, summary: string,
];

const BJJ_SOURCE = 'https://en.wikipedia.org/wiki/List_of_Brazilian_jiu-jitsu_techniques';

const guides: Record<string, Pick<Technique, 'steps' | 'keyPoints' | 'safety'>> = {
  Position: {
    steps: ['Sichere Rahmen, Griffe und Kopfposition herstellen.', 'Hüfte und Schultern so ausrichten, dass die Position stabil bleibt.', 'Kontrolle halten und erst dann zum nächsten Angriff oder Übergang wechseln.'],
    keyPoints: ['Position vor Angriff', 'Innenraum kontrollieren', 'Balance bewahren'],
    safety: 'Positionswechsel kontrolliert ausführen und keine Gelenke durch Körpergewicht unkontrolliert belasten.',
  },
  Bewegung: {
    steps: ['Stabile Ausgangshaltung und geschützte Armposition einnehmen.', 'Die Bewegung zunächst langsam und technisch sauber ausführen.', 'Abstand, Winkel oder Hüftposition für die nächste Aktion verbessern.'],
    keyPoints: ['Saubere Haltung', 'Kontrolliertes Tempo', 'Winkel verbessern'],
    safety: 'Bewegungen zunächst ohne Widerstand lernen und Geschwindigkeit erst mit sicherer Technik steigern.',
  },
  Submission: {
    steps: ['Position und Fluchtwege kontrollieren, bevor Druck entsteht.', 'Griffe beziehungsweise Beinposition vollständig und ohne Ruck sichern.', 'Die Submission langsam anziehen und beim Tap sofort vollständig lösen.'],
    keyPoints: ['Kontrolle vor Finish', 'Langsam Druck erhöhen', 'Tap sofort respektieren'],
    safety: 'Submissions nur mit qualifizierter Anleitung trainieren. Regeln hängen von Alter, Gürtelklasse und Gi/No-Gi ab.',
  },
  Sweep: {
    steps: ['Griffe oder Hooks sichern und die Stützpunkte des Partners erkennen.', 'Gleichgewicht in die gewünschte Richtung brechen.', 'Sweep abschließen und die obere Position sofort stabilisieren.'],
    keyPoints: ['Stützpunkt entfernen', 'Kuzushi erzeugen', 'Oben stabilisieren'],
    safety: 'Knie und Sprunggelenke nicht seitlich erzwingen und dem Partner Raum für eine sichere Fallbewegung lassen.',
  },
  Guardpass: {
    steps: ['Haltung sichern und gefährliche Griffe oder Hooks lösen.', 'Beine und Hüfte kontrollieren, während ein Passwinkel entsteht.', 'An den Beinen vorbeigehen und Side Control oder Mount stabilisieren.'],
    keyPoints: ['Haltung zuerst', 'Hüfte kontrollieren', 'Passposition sichern'],
    safety: 'Keinen unkontrollierten Druck auf Knie oder Hals ausüben; Gewicht schrittweise übertragen.',
  },
  Escape: {
    steps: ['Akute Submission-Gefahr zuerst beseitigen und sichere Rahmen bilden.', 'Mit Brücke, Hüftbewegung oder Winkel Raum erzeugen.', 'Knie oder Arme zurück in den Innenraum bringen und eine stabile Position herstellen.'],
    keyPoints: ['Gefahr zuerst lösen', 'Rahmen statt Kraft', 'Guard oder Stand sichern'],
    safety: 'Nicht explosiv gegen fixierte Gelenke arbeiten. Bei fest sitzender Submission rechtzeitig tappen.',
  },
  Takedown: {
    steps: ['Griff, Kopfposition und Distanz kontrollieren.', 'Das Gleichgewicht brechen und den Einstieg mit stabiler Haltung ausführen.', 'Den Partner kontrolliert zu Boden bringen und eine obere Position sichern.'],
    keyPoints: ['Kuzushi vor Wurf', 'Rücken stabil', 'Landung kontrollieren'],
    safety: 'Nur auf geeigneten Matten und mit sicherer Falltechnik trainieren. Verbotene Würfe und Beingriffe regelabhängig beachten.',
  },
};

function expand(item: CompactTechnique): Technique {
  const [id, de, en, ja, romaji, category, subcategory, position, summary] = item;
  return {
    id, names: { de, en, ja, romaji }, category, subcategory, position, summary,
    ...guides[category],
    sourceTitle: 'Wikipedia – Liste der BJJ-Techniken',
    sourceUrl: BJJ_SOURCE,
  };
}

const compact: CompactTechnique[] = [
  // Guard- und Kontrollpositionen
  ['closed-guard', 'Geschlossene Guard', 'Closed guard', 'クローズドガード', 'Kurōzudo gādo', 'Position', 'Guard', 'Bottom', 'Beide Beine schließen sich um die Hüfte des Partners und begrenzen dessen Abstand und Haltung.'],
  ['open-guard', 'Offene Guard', 'Open guard', 'オープンガード', 'Ōpun gādo', 'Position', 'Guard', 'Bottom', 'Die Beine kontrollieren Abstand und Winkel, ohne dass sie um die Hüfte geschlossen sind.'],
  ['half-guard', 'Half Guard', 'Half guard', 'ハーフガード', 'Hāfu gādo', 'Position', 'Guard', 'Bottom', 'Ein Bein des oberen Partners wird zwischen den eigenen Beinen kontrolliert.'],
  ['knee-shield', 'Knee-Shield-Guard', 'Knee shield half guard', 'ニーシールド', 'Nī shīrudo', 'Position', 'Guard', 'Bottom Half Guard', 'Das obere Knie bildet einen Schild, der Distanz und Oberkörperdruck kontrolliert.'],
  ['deep-half', 'Deep Half Guard', 'Deep half guard', 'ディープハーフガード', 'Dīpu hāfu gādo', 'Position', 'Guard', 'Bottom Half Guard', 'Der Unterkörper wird tief unter den Schwerpunkt des Partners gebracht, um dessen Basis anzugreifen.'],
  ['butterfly-guard', 'Butterfly Guard', 'Butterfly guard', 'バタフライガード', 'Batafurai gādo', 'Position', 'Guard', 'Seated Guard', 'Beide Füße dienen als innere Hooks an den Oberschenkeln des Partners.'],
  ['spider-guard', 'Spider Guard', 'Spider guard', 'スパイダーガード', 'Supaidā gādo', 'Position', 'Gi Guard', 'Bottom', 'Ärmelgriffe und Füße an den Armen kontrollieren Haltung und Abstand.'],
  ['lasso-guard', 'Lasso Guard', 'Lasso guard', 'ラッソーガード', 'Rassō gādo', 'Position', 'Gi Guard', 'Bottom', 'Ein Bein wickelt sich mit Ärmelkontrolle um den Arm des Partners.'],
  ['de-la-riva', 'De-la-Riva-Guard', 'De La Riva guard', 'デラヒーバガード', 'Dera hība gādo', 'Position', 'Open Guard', 'Bottom', 'Ein äußerer Hook um das Standbein kontrolliert Drehung, Abstand und Rückenexposition.'],
  ['reverse-de-la-riva', 'Reverse-De-la-Riva-Guard', 'Reverse De La Riva guard', 'リバースデラヒーバ', 'Ribāsu dera hība', 'Position', 'Open Guard', 'Bottom', 'Ein innerer Hook am nahen Bein stört Knee-Cut- und Druckpässe.'],
  ['x-guard', 'X-Guard', 'X-guard', 'Xガード', 'Ekkusu gādo', 'Position', 'Open Guard', 'Bottom', 'Überkreuzte Bein-Hooks kontrollieren ein Standbein unter dem Schwerpunkt des Partners.'],
  ['single-leg-x', 'Single-Leg-X', 'Single-leg X guard', 'シングルレッグX', 'Shinguru reggu ekkusu', 'Position', 'Ashi Garami', 'Bottom', 'Die Beine umschließen ein Bein und kontrollieren Hüfte und Knie des stehenden Partners.'],
  ['fifty-fifty', '50/50-Guard', '50/50 guard', 'フィフティフィフティガード', 'Fifuti fifuti gādo', 'Position', 'Leg Entanglement', 'Bottom / Neutral', 'Beide Personen kontrollieren spiegelbildlich jeweils ein Bein des anderen.'],
  ['ashi-garami', 'Beinverwicklung', 'Ashi garami', '足緘', 'Ashi-garami', 'Position', 'Leg Entanglement', 'Bottom / Neutral', 'Eine Gruppe von Beinpositionen kontrolliert Hüfte, Knie und Fußlinie für Sweeps oder Leglocks.'],
  ['saddle', 'Saddle / 411', 'Saddle / inside sankaku', 'インサイド三角', 'Insaido sankaku', 'Position', 'Leg Entanglement', 'Bottom / Top', 'Beide Beine kontrollieren ein Bein von innen und begrenzen die Hüftrotation.'],
  ['rubber-guard', 'Rubber Guard', 'Rubber guard', 'ラバーガード', 'Rabā gādo', 'Position', 'Guard', 'Bottom', 'Eine hohe Beinposition kontrolliert Haltung und Schulter, häufig aus der geschlossenen Guard.'],
  ['worm-guard', 'Worm Guard', 'Worm guard', 'ワームガード', 'Wāmu gādo', 'Position', 'Lapel Guard', 'Bottom Gi', 'Ein gelöster Reversstoff wird um ein Bein geführt, um Haltung und Bewegungsfreiheit zu binden.'],
  ['lapel-guard', 'Lapel Guard', 'Lapel guard', 'ラペルガード', 'Raperu gādo', 'Position', 'Gi Guard', 'Bottom Gi', 'Das gegnerische Revers wird als zusätzliche Verbindung für Kontrolle und Sweeps genutzt.'],
  ['inverted-guard', 'Invertierte Guard', 'Inverted guard', 'インバーテッドガード', 'Inbāteddo gādo', 'Position', 'Open Guard', 'Bottom', 'Die Hüfte dreht unter den eigenen Schultern hindurch, um Beinposition und Retention zu erhalten.'],
  ['octopus-guard', 'Octopus Guard', 'Octopus guard', 'オクトパスガード', 'Okutopasu gādo', 'Position', 'Half Guard', 'Bottom', 'Ein Rücken- oder Taillengriff umgeht den Crossface und öffnet Winkel zum Rücken oder Sweep.'],
  ['side-control', 'Seitkontrolle', 'Side control', '横四方固', 'Yoko-shiho-gatame', 'Position', 'Top Control', 'Top', 'Der Oberkörper wird quer über Brust und Hüfte des unteren Partners kontrolliert.'],
  ['kesa-gatame', 'Schärpenhaltegriff', 'Scarf hold', '袈裟固', 'Kesa-gatame', 'Position', 'Top Control', 'Top', 'Kopf und naher Arm werden aus einer seitlichen Hüftposition kontrolliert.'],
  ['north-south', 'Nord-Süd-Position', 'North-south position', '上四方固', 'Kami-shiho-gatame', 'Position', 'Top Control', 'Top', 'Der Oberkörper liegt entgegengesetzt über Kopf und Schultern des Partners.'],
  ['knee-on-belly', 'Knie auf Bauch', 'Knee-on-belly', '浮固', 'Uki-gatame', 'Position', 'Top Control', 'Top', 'Ein Knie kontrolliert den Rumpf, während das andere Bein Beweglichkeit und Basis erhält.'],
  ['mount', 'Mount', 'Mount', '縦四方固', 'Tate-shiho-gatame', 'Position', 'Top Control', 'Top', 'Die Beine befinden sich beidseits des Rumpfs, während die Hüfte den Oberkörper kontrolliert.'],
  ['back-control', 'Rückenkontrolle', 'Back control', 'バックコントロール', 'Bakku kontorōru', 'Position', 'Top Control', 'Back', 'Brust-Rücken-Verbindung und Hooks oder Body Triangle begrenzen die Flucht.'],
  ['turtle', 'Schildkrötenposition', 'Turtle position', '亀', 'Kame', 'Position', 'Defensive Position', 'Bottom', 'Knie und Ellenbogen bilden am Boden eine kompakte Schutzstruktur.'],

  // Grundbewegungen und Kontrollen
  ['technical-standup', 'Technisches Aufstehen', 'Technical stand-up', 'テクニカルスタンドアップ', 'Tekunikaru sutando appu', 'Bewegung', 'Grundbewegung', 'Ground to Standing', 'Eine geschützte Methode, vom Boden aufzustehen und dabei Abstand zum Partner zu halten.'],
  ['forward-roll', 'Vorwärtsrolle', 'Forward roll', '前回り受身', 'Mae-mawari-ukemi', 'Bewegung', 'Fallschule', 'Standing / Ground', 'Die Rolle verteilt Bewegung über Schulter und Rücken, ohne den Kopf zu belasten.'],
  ['backward-roll', 'Rückwärtsrolle', 'Backward roll', '後方回転', 'Kōhō kaiten', 'Bewegung', 'Grundbewegung', 'Ground', 'Eine Rückwärtsrotation unterstützt Guard-Retention, Inversion und sichere Bewegung.'],
  ['bridge', 'Brücke', 'Bridge', 'ブリッジ', 'Burijji', 'Bewegung', 'Grundbewegung', 'Bottom', 'Explosive Hüftstreckung erzeugt Raum und verschiebt das Gewicht des Partners.'],
  ['hip-heist', 'Hüftwechsel', 'Hip heist', 'ヒップハイスト', 'Hippu haisuto', 'Bewegung', 'Grundbewegung', 'Ground', 'Die Hüfte wechselt unter Belastung die Seite und führt häufig zum Aufstehen oder Rückenangriff.'],
  ['granby-roll', 'Granby-Rolle', 'Granby roll', 'グランビーロール', 'Guranbī rōru', 'Bewegung', 'Grundbewegung', 'Turtle / Guard', 'Eine Schulterrolle schafft Winkel für Guard-Recovery oder schützt den Rücken.'],
  ['arm-drag', 'Armzug', 'Arm drag', 'アームドラッグ', 'Āmu doraggu', 'Bewegung', 'Control', 'Standing / Guard', 'Der Arm wird an der Körpermitte vorbeigezogen, um seitlichen Winkel oder Rückenposition zu gewinnen.'],
  ['pummeling', 'Pummeling', 'Pummeling', 'パメリング', 'Pameringu', 'Bewegung', 'Clinch', 'Standing', 'Wechselnde Underhooks trainieren die innere Armposition im Clinch.'],
  ['sprawl', 'Sprawl-Abwehr', 'Sprawl', 'スプロール', 'Supurōru', 'Bewegung', 'Takedown Defense', 'Standing', 'Hüfte und Beine bewegen sich zurück, um einen Beinangriff abzufangen.'],
  ['sit-out', 'Sit-out', 'Sit-out', 'シットアウト', 'Shitto auto', 'Bewegung', 'Turtle Movement', 'Ground', 'Die Hüfte dreht unter dem Körper hindurch, um Front-Headlock- oder Turtle-Kontrolle zu lösen.'],

  // Würge- und Hebeltechniken
  ['arm-triangle', 'Arm-Dreieckswürger', 'Arm-triangle choke', '肩固', 'Kata-gatame', 'Submission', 'Würgetechnik', 'Mount / Side Control', 'Kopf und eigener Arm des Partners bilden mit dem angreifenden Arm ein Würgedreieck.'],
  ['darce', 'D’Arce-Würger', 'D’Arce choke', 'ダースチョーク', 'Dāsu chōku', 'Submission', 'Würgetechnik', 'Front Headlock', 'Der Arm läuft unter Achsel und Hals hindurch und schließt einen Arm-Kopf-Würger.'],
  ['anaconda', 'Anaconda-Würger', 'Anaconda choke', 'アナコンダチョーク', 'Anakonda chōku', 'Submission', 'Würgetechnik', 'Front Headlock', 'Ein Arm-Kopf-Würger wird aus dem Front Headlock geschlossen und häufig durch Rollen verdichtet.'],
  ['north-south-choke', 'Nord-Süd-Würger', 'North-south choke', 'ノースサウスチョーク', 'Nōsu sausu chōku', 'Submission', 'Würgetechnik', 'North-South', 'Brust, Arm und Rippen kontrollieren den Hals aus der Nord-Süd-Position.'],
  ['ezekiel', 'Ezekiel-Würger', 'Ezekiel choke', '袖車絞', 'Sode-guruma-jime', 'Submission', 'Gi Choke', 'Mount / Guard', 'Die eigenen Ärmel bilden eine Schlinge um den Hals; Varianten funktionieren auch ohne Gi.'],
  ['bow-arrow', 'Pfeil-und-Bogen-Würger', 'Bow-and-arrow choke', 'ボウアンドアローチョーク', 'Bō ando arō chōku', 'Submission', 'Gi Choke', 'Back Control', 'Kragen- und Beinkontrolle spannen den Körper wie einen Bogen gegen den Hals.'],
  ['baseball-choke', 'Baseballschläger-Würger', 'Baseball bat choke', 'ベースボールバットチョーク', 'Bēsubōru batto chōku', 'Submission', 'Gi Choke', 'Guard / Side Control', 'Zwei nahe Kragengriffe rotieren wie an einem Baseballschläger und schließen den Hals.'],
  ['loop-choke', 'Loop Choke', 'Loop choke', 'ループチョーク', 'Rūpu chōku', 'Submission', 'Gi Choke', 'Guard / Front Headlock', 'Ein tiefer Kragengriff bildet beim Abtauchen des Kopfes eine Schlinge um den Hals.'],
  ['clock-choke', 'Uhrzeiger-Würger', 'Clock choke', 'クロックチョーク', 'Kurokku chōku', 'Submission', 'Gi Choke', 'Top Turtle', 'Kragengriffe bleiben fixiert, während die Beine kreisförmig um den Partner laufen.'],
  ['paper-cutter', 'Papierschneider-Würger', 'Paper cutter choke', 'ペーパーカッターチョーク', 'Pēpā kattā chōku', 'Submission', 'Gi Choke', 'Side Control', 'Untergriff und Kragengriff erzeugen einen schneidenden Unterarmdruck am Hals.'],
  ['cross-collar', 'Kreuzkragen-Würger', 'Cross-collar choke', '十字絞', 'Jūji-jime', 'Submission', 'Gi Choke', 'Guard / Mount', 'Gekreuzte tiefe Kragengriffe kontrollieren beide Seiten des Halses.'],
  ['gogoplata', 'Gogoplata', 'Gogoplata', 'ゴゴプラタ', 'Gogopurata', 'Submission', 'Würgetechnik', 'High Guard', 'Schienbein oder Fußrist drückt aus hoher Guard gegen den Hals.'],
  ['peruvian-necktie', 'Peruanische Krawatte', 'Peruvian necktie', 'ペルビアンネクタイ', 'Perubian nekutai', 'Submission', 'Würgetechnik', 'Front Headlock', 'Arme und Beine verbinden sich aus dem Front Headlock zu einem Arm-Kopf-Würger.'],
  ['von-flue', 'Von-Flue-Würger', 'Von Flue choke', 'ヴォンフルーチョーク', 'Von furū chōku', 'Submission', 'Würgetechnik', 'Top Side Control', 'Schulterdruck würgt einen Partner, der aus unterer Position an einer Guillotine festhält.'],
  ['bulldog-choke', 'Bulldog-Würger', 'Bulldog choke', 'ブルドッグチョーク', 'Burudoggu chōku', 'Submission', 'Würgetechnik', 'Side / Turtle', 'Ein kopfseitiger Arm umschließt den Hals ohne vollständige Rückenkontrolle.'],
  ['straight-ankle', 'Gerader Fußhebel', 'Straight ankle lock', '足挫', 'Ashi-hishigi', 'Submission', 'Beinhebel', 'Ashi Garami', 'Der Unterarm wirkt als Hebelkante am Sprunggelenk, während Bein und Hüfte kontrolliert bleiben.'],
  ['kneebar', 'Gerader Kniehebel', 'Kneebar', '膝十字固', 'Hiza-juji-gatame', 'Submission', 'Beinhebel', 'Leg Entanglement', 'Das Knie wird ähnlich einem Armbar zwischen Hüfte und Armen kontrolliert und gestreckt.'],
  ['heel-hook-inside', 'Innerer Heel Hook', 'Inside heel hook', 'インサイドヒールフック', 'Insaido hīru fukku', 'Submission', 'Rotations-Beinhebel', 'Saddle / 50-50', 'Ferse und Knie werden in gegensätzlicher Rotation kontrolliert; die Belastung erreicht das Knie sehr schnell.'],
  ['heel-hook-outside', 'Äußerer Heel Hook', 'Outside heel hook', 'アウトサイドヒールフック', 'Autosaido hīru fukku', 'Submission', 'Rotations-Beinhebel', 'Ashi Garami', 'Die außen gefangene Ferse überträgt Rotation über Sprunggelenk und Knie.'],
  ['toe-hold', 'Toe Hold', 'Toe hold', 'トーホールド', 'Tō hōrudo', 'Submission', 'Rotations-Beinhebel', 'Leg Entanglement', 'Ein Vierergriff am Fuß erzeugt Beugung und Rotation am Sprunggelenk.'],
  ['calf-slicer', 'Wadenquetscher', 'Calf slicer', 'カーフスライサー', 'Kāfu suraisā', 'Submission', 'Kompressionshebel', 'Leg Entanglement', 'Schienbein oder Unterarm wirkt als Keil zwischen Ober- und Unterschenkel.'],
  ['biceps-slicer', 'Bizepsquetscher', 'Biceps slicer', 'バイセップスライサー', 'Baisepusu suraisā', 'Submission', 'Kompressionshebel', 'Arm Entanglement', 'Ein harter Keil komprimiert den gebeugten Arm zwischen Unter- und Oberarm.'],
  ['omoplata', 'Omoplata', 'Omoplata', 'オモプラッタ', 'Omopuratta', 'Submission', 'Schulterhebel', 'Guard', 'Das Bein kontrolliert Schulter und Arm, während die Hüfte zur Schulterrotation aufrichtet.'],
  ['wrist-lock', 'Handgelenkhebel', 'Wrist lock', '手首固', 'Tekubi-gatame', 'Submission', 'Gelenkhebel', 'Multiple', 'Hand und Unterarm werden fixiert, um das Handgelenk kontrolliert zu beugen oder zu drehen.'],
  ['mir-lock', 'Mir Lock', 'Mir lock', 'ミアロック', 'Mia rokku', 'Submission', 'Schulterhebel', 'Open Guard', 'Ein gestreckter Arm wird mit Oberkörper und Beinen in Schulterrotation kontrolliert.'],
  ['tarikoplata', 'Tarikoplata', 'Tarikoplata', 'タリコプラタ', 'Tarikopurata', 'Submission', 'Schulterhebel', 'Top / Guard', 'Eine Beinfigur kontrolliert den Kimura-Arm und ermöglicht Schulterrotation mit dem Unterkörper.'],
  ['twister', 'Twister', 'Twister', 'ツイスター', 'Tsuisutā', 'Submission', 'Wirbelsäulenhebel', 'Back / Half Guard', 'Hüfte und Oberkörper werden gegeneinander fixiert und kontrolliert rotiert.'],
  ['banana-split', 'Banana Split', 'Banana split', 'バナナスプリット', 'Banana supuritto', 'Submission', 'Hüfthebel', 'Truck Position', 'Beide Beine werden voneinander getrennt, um Hüfte und Adduktoren zu belasten.'],

  // Sweeps
  ['hip-bump-sweep', 'Hüftstoß-Sweep', 'Hip bump sweep', 'ヒップバンプスイープ', 'Hippu banpu suīpu', 'Sweep', 'Closed Guard', 'Bottom Guard', 'Ein Aufrichten und kräftiger Hüftstoß kippen den abgestützten Partner über eine Seite.'],
  ['flower-sweep', 'Flower Sweep', 'Flower sweep', 'フラワースイープ', 'Furawā suīpu', 'Sweep', 'Closed Guard', 'Bottom Guard', 'Arm- und Beinkontrolle verbinden sich mit einer Pendelbewegung des freien Beins.'],
  ['pendulum-sweep', 'Pendel-Sweep', 'Pendulum sweep', 'ペンデュラムスイープ', 'Pendyuramu suīpu', 'Sweep', 'Closed Guard', 'Bottom Guard', 'Das freie Bein schwingt als Pendel, während Arm und Bein der Fallseite kontrolliert sind.'],
  ['lumberjack-sweep', 'Lumberjack Sweep', 'Lumberjack sweep', 'ランバージャックスイープ', 'Ranbājakku suīpu', 'Sweep', 'Closed Guard', 'Bottom Guard', 'Beide Knöchel werden beim Aufstehen kontrolliert und die Knie nach außen geöffnet.'],
  ['waiter-sweep', 'Kellner-Sweep', 'Waiter sweep', 'ウェイタースイープ', 'Weitā suīpu', 'Sweep', 'Deep Half', 'Bottom', 'Das kontrollierte Bein wird wie ein Tablett angehoben, um Basis und Richtung des Partners zu brechen.'],
  ['old-school-sweep', 'Old-School-Sweep', 'Old school sweep', 'オールドスクールスイープ', 'Ōrudo sukūru suīpu', 'Sweep', 'Half Guard', 'Bottom', 'Ein Underhook und Griff am entfernten Fuß führen zum Aufstehen und Vorwärtskippen.'],
  ['john-wayne-sweep', 'John-Wayne-Sweep', 'John Wayne sweep', 'ジョンウェインスイープ', 'Jon wein suīpu', 'Sweep', 'Half Guard', 'Bottom', 'Eine schnelle Knie- und Hüftrotation kippt den Druck des oberen Partners seitlich um.'],
  ['butterfly-sweep', 'Butterfly-Sweep', 'Butterfly sweep', 'バタフライスイープ', 'Batafurai suīpu', 'Sweep', 'Butterfly Guard', 'Bottom', 'Ein innerer Hook hebt, während Oberkörperkontrolle den Partner diagonal über die Schulter führt.'],
  ['tripod-sweep', 'Dreipunkt-Sweep', 'Tripod sweep', 'トライポッドスイープ', 'Toraipoddo suīpu', 'Sweep', 'Open Guard', 'Bottom', 'Fuß, Knöchelgriff und Hook entfernen drei Stützrichtungen eines stehenden Partners.'],
  ['sickle-sweep', 'Sichel-Sweep', 'Sickle sweep', 'シックスルスイープ', 'Shikkuru suīpu', 'Sweep', 'Open Guard', 'Bottom', 'Ein Bein blockiert den Fuß, während das andere die Hüfte rückwärts drückt.'],
  ['de-la-riva-sweep', 'De-la-Riva-Sweep', 'De La Riva sweep', 'デラヒーバスイープ', 'Dera hība suīpu', 'Sweep', 'De La Riva', 'Bottom', 'Hook, Griff und Winkel stören das Standbein und führen zu Rückenposition oder Topposition.'],
  ['x-guard-sweep', 'X-Guard-Sweep', 'X-guard sweep', 'Xガードスイープ', 'Ekkusu gādo suīpu', 'Sweep', 'X-Guard', 'Bottom', 'Die X-Hooks strecken und drehen das belastete Bein aus seiner Basis.'],
  ['single-leg-x-sweep', 'Single-Leg-X-Sweep', 'Single-leg X sweep', 'シングルレッグXスイープ', 'Shinguru reggu ekkusu suīpu', 'Sweep', 'Single-Leg-X', 'Bottom', 'Hüftdruck und Kontrolle am Fuß bringen den stehenden Partner aus dem Gleichgewicht.'],
  ['omoplata-sweep', 'Omoplata-Sweep', 'Omoplata sweep', 'オモプラッタスイープ', 'Omopuratta suīpu', 'Sweep', 'Guard', 'Bottom', 'Die Omoplata-Kontrolle wird genutzt, um den Partner vorwärts zu rollen und oben zu landen.'],
  ['technical-sweep', 'Technical Sweep', 'Technical sweep', 'テクニカルスイープ', 'Tekunikaru suīpu', 'Sweep', 'Seated Guard', 'Bottom', 'Ein Hand- und Fußposten unterstützt das technische Aufstehen gegen ein kontrolliertes Bein.'],
  ['balloon-sweep', 'Ballon-Sweep', 'Balloon sweep', 'バルーンスイープ', 'Barūn suīpu', 'Sweep', 'Open Guard', 'Bottom', 'Füße oder Knie heben den vorwärts belasteten Partner über den eigenen Schwerpunkt.'],

  // Guard-Pässe
  ['torreando-pass', 'Toreando-Pass', 'Toreando pass', 'トレアンドパス', 'Toreando pasu', 'Guardpass', 'Outside Pass', 'Top Open Guard', 'Beide Beine werden seitlich gelenkt, während der Körper außen an der Hüfte vorbeigeht.'],
  ['knee-cut-pass', 'Knee-Cut-Pass', 'Knee slice pass', 'ニーカットパス', 'Nī katto pasu', 'Guardpass', 'Pressure Pass', 'Top Half/Open Guard', 'Ein Knie schneidet über den Oberschenkel, während Oberkörper und Hüfte kontrolliert bleiben.'],
  ['x-pass', 'X-Pass', 'X-pass', 'Xパス', 'Ekkusu pasu', 'Guardpass', 'Standing Pass', 'Top Open Guard', 'Bein- und Hüftgriffe öffnen einen diagonalen Schritt an der Guard vorbei.'],
  ['leg-drag-pass', 'Leg-Drag-Pass', 'Leg drag pass', 'レッグドラッグパス', 'Reggu doraggu pasu', 'Guardpass', 'Outside Pass', 'Top Open Guard', 'Beide Beine werden auf eine Körperseite gelenkt, um Hüfte und Rückenrotation zu blockieren.'],
  ['over-under-pass', 'Over-Under-Pass', 'Over-under pass', 'オーバーアンダーパス', 'Ōbā andā pasu', 'Guardpass', 'Pressure Pass', 'Top Open Guard', 'Ein Arm kontrolliert über einem Bein, der andere unter dem Gegenbein, während der Oberkörper Druck ausübt.'],
  ['double-under-pass', 'Double-Under-Pass', 'Double-under pass', 'ダブルアンダーパス', 'Daburu andā pasu', 'Guardpass', 'Stack Pass', 'Top Open Guard', 'Beide Arme unter den Beinen heben die Hüfte und stapeln die Guard für einen seitlichen Pass.'],
  ['stack-pass', 'Stack-Pass', 'Stack pass', 'スタックパス', 'Sutakku pasu', 'Guardpass', 'Pressure Pass', 'Top Guard', 'Die Hüfte wird über die Schultern gestapelt, um Beinrahmen zu verkürzen und seitlich vorbeizugehen.'],
  ['body-lock-pass', 'Body-Lock-Pass', 'Body lock pass', 'ボディロックパス', 'Bodi rokku pasu', 'Guardpass', 'Pressure Pass', 'Top Butterfly', 'Ein Griff um den Rumpf bindet die Hüfte, während die Beine schrittweise überwunden werden.'],
  ['headquarters-pass', 'Headquarters-Pass', 'Headquarters pass', 'ヘッドクォーターパス', 'Heddokuōtā pasu', 'Guardpass', 'Passing Hub', 'Top Open Guard', 'Eine stabile zentrale Beinposition schafft Optionen für Knee Cut, Smash oder Backstep.'],
  ['smash-pass', 'Smash-Pass', 'Smash pass', 'スマッシュパス', 'Sumasshu pasu', 'Guardpass', 'Pressure Pass', 'Top Open Guard', 'Die Knie werden zusammengelegt und seitlich zum Boden gedrückt, bevor der Oberkörper folgt.'],
  ['backstep-pass', 'Backstep-Pass', 'Backstep pass', 'バックステップパス', 'Bakku suteppu pasu', 'Guardpass', 'Rotational Pass', 'Top Half Guard', 'Ein großer Rückwärtsschritt wechselt Hüftseite und Richtung, um Half-Guard-Hooks zu lösen.'],
  ['long-step-pass', 'Long-Step-Pass', 'Long step pass', 'ロングステップパス', 'Rongu suteppu pasu', 'Guardpass', 'Outside Pass', 'Top Open Guard', 'Ein weiter Schritt und Hüftdrehung ziehen die Beine aus der Passlinie.'],
  ['tripod-pass', 'Tripod-Pass', 'Tripod pass', 'トライポッドパス', 'Toraipoddo pasu', 'Guardpass', 'Pressure Pass', 'Top Half Guard', 'Kopf und Füße bilden eine Dreipunktbasis, während das gefangene Knie befreit wird.'],
  ['weave-pass', 'Weave-Pass', 'Weave pass', 'ウィーブパス', 'Wību pasu', 'Guardpass', 'Pressure Pass', 'Top Knee Shield', 'Ein Arm verwebt die Beine und dreht Knie und Hüfte zusammen zur Seite.'],
  ['folding-pass', 'Folding-Pass', 'Folding pass', 'フォールディングパス', 'Fōrudingu pasu', 'Guardpass', 'Pressure Pass', 'Top Open Guard', 'Beide Knie werden in eine Richtung gefaltet und mit Hüftdruck fixiert.'],
  ['single-under-pass', 'Single-Under-Pass', 'Single-under pass', 'シングルアンダーパス', 'Shinguru andā pasu', 'Guardpass', 'Stack Pass', 'Top Open Guard', 'Ein Arm hebt ein Bein, während das andere kontrolliert und der Passwinkel geöffnet wird.'],
  ['double-knee-pass', 'Double-Knee-Pass', 'Double knee pass', 'ダブルニーパス', 'Daburu nī pasu', 'Guardpass', 'Kneeling Pass', 'Top Open Guard', 'Beide Knie bewegen sich eng an den Beinen vorbei, während Hüfte und Oberkörper verbunden bleiben.'],
  ['north-south-pass', 'Nord-Süd-Pass', 'North-south pass', 'ノースサウスパス', 'Nōsu sausu pasu', 'Guardpass', 'Outside Pass', 'Top Open Guard', 'Nach dem Überwinden der Beine wird zunächst Nord-Süd statt Side Control stabilisiert.'],

  // Escapes und Guard-Recovery
  ['elbow-escape', 'Ellenbogen-Knie-Befreiung', 'Elbow escape', 'エルボーエスケープ', 'Erubō esukēpu', 'Escape', 'Mount Escape', 'Bottom Mount', 'Rahmen und Hüftflucht schaffen Raum, um ein Knie zurück zwischen die Körper zu bringen.'],
  ['kipping-escape', 'Kipping Escape', 'Kipping escape', 'キッピングエスケープ', 'Kippingu esukēpu', 'Escape', 'Mount Escape', 'Bottom Mount', 'Kurze rhythmische Hüftbewegungen und Armrahmen heben die Hüfte für Beinverwicklungen.'],
  ['heel-drag-escape', 'Fersen-Zieh-Befreiung', 'Heel drag mount escape', 'ヒールドラッグエスケープ', 'Hīru doraggu esukēpu', 'Escape', 'Mount Escape', 'Bottom Mount', 'Der Fuß fängt die gegnerische Ferse und zieht sie in eine Half Guard.'],
  ['ghost-escape', 'Ghost Escape', 'Ghost escape', 'ゴーストエスケープ', 'Gōsuto esukēpu', 'Escape', 'Side Control Escape', 'Bottom Side Control', 'Unterarmrahmen und eine Rückwärtsbewegung lassen den Körper unter der Kontrolle herausgleiten.'],
  ['reguard-side-control', 'Guard-Recovery aus Seitkontrolle', 'Side-control guard recovery', 'ガードリカバリー', 'Gādo rikabarī', 'Escape', 'Side Control Escape', 'Bottom Side Control', 'Rahmen und Hüftflucht bringen Knie und Schienbein zurück zwischen beide Körper.'],
  ['underhook-escape', 'Underhook-Befreiung', 'Underhook side-control escape', 'アンダーフックエスケープ', 'Andā fukku esukēpu', 'Escape', 'Side Control Escape', 'Bottom Side Control', 'Ein Underhook öffnet den Weg auf die Seite, zum Knie oder zum Rücken des Partners.'],
  ['north-south-escape', 'Nord-Süd-Befreiung', 'North-south escape', 'ノースサウスエスケープ', 'Nōsu sausu esukēpu', 'Escape', 'Pin Escape', 'Bottom North-South', 'Rahmen an Hüfte und Schulter schaffen den Winkel für Drehung und Guard-Recovery.'],
  ['kesa-escape', 'Kesa-Gatame-Befreiung', 'Scarf-hold escape', '袈裟固脱出', 'Kesa-gatame dasshutsu', 'Escape', 'Pin Escape', 'Bottom Kesa-Gatame', 'Brücke, Rahmen und Hüftposition lösen Kopf-Arm-Kontrolle oder drehen den Partner.'],
  ['back-escape-shoulder-floor', 'Rückenbefreiung zur Mattenseite', 'Back escape to mat side', 'バックエスケープ', 'Bakku esukēpu', 'Escape', 'Back Escape', 'Bottom Back Control', 'Kopf und Schultern erreichen die sichere Mattenseite, bevor Hüfte und Beine aus den Hooks gleiten.'],
  ['body-triangle-escape', 'Body-Triangle-Befreiung', 'Body triangle escape', 'ボディトライアングルエスケープ', 'Bodi toraianguru esukēpu', 'Escape', 'Back Escape', 'Bottom Back Control', 'Die Schlossseite wird positioniert und kontrolliert geöffnet, bevor der Oberkörper flieht.'],
  ['turtle-guard-recovery', 'Guard-Recovery aus Turtle', 'Turtle to guard', '亀からガード', 'Kame kara gādo', 'Escape', 'Turtle Escape', 'Bottom Turtle', 'Ellenbogen-Knie-Verbindung und Hüftdrehung bringen die Beine wieder vor den Partner.'],
  ['front-headlock-escape', 'Front-Headlock-Befreiung', 'Front headlock escape', 'フロントヘッドロックエスケープ', 'Furonto heddorokku esukēpu', 'Escape', 'Headlock Escape', 'Turtle / Standing', 'Handkampf, Haltung und seitlicher Winkel entfernen Halskontrolle und öffnen den Ausgang.'],
  ['armbar-hitchhiker', 'Hitchhiker-Befreiung', 'Hitchhiker armbar escape', 'ヒッチハイカーエスケープ', 'Hitchihaikā esukēpu', 'Escape', 'Submission Escape', 'Bottom Armbar', 'Daumenrotation und Laufbewegung folgen der offenen Richtung des Armhebels.'],
  ['triangle-posture-escape', 'Triangle-Haltungsbefreiung', 'Triangle posture escape', '三角絞脱出', 'Sankaku-jime dasshutsu', 'Escape', 'Submission Escape', 'Inside Triangle', 'Haltung, Kniekontrolle und Winkelkorrektur öffnen das Beindreieck, bevor es fest geschlossen ist.'],
  ['straight-ankle-escape', 'Fußhebel-Befreiung', 'Straight ankle-lock escape', '足挫脱出', 'Ashi-hishigi dasshutsu', 'Escape', 'Submission Escape', 'Leg Entanglement', 'Knie- und Fußlinie werden befreit, bevor die kontrollierte Ferse den Hebel verstärkt.'],

  // Takedowns und Würfe
  ['double-leg', 'Doppelbeinangriff', 'Double-leg takedown', '双手刈', 'Morote-gari', 'Takedown', 'Wrestling', 'Standing', 'Beide Beine werden kontrolliert und der Partner über Winkel oder Vorwärtsdruck zu Boden gebracht.'],
  ['ankle-pick', 'Knöchel-Pick', 'Ankle pick', 'アンクルピック', 'Ankuru pikku', 'Takedown', 'Wrestling', 'Standing', 'Kopf- oder Armkontrolle belastet ein Bein, während die Hand den Knöchel entfernt.'],
  ['knee-tap', 'Knie-Tap', 'Knee tap', 'ニータップ', 'Nī tappu', 'Takedown', 'Wrestling', 'Standing Clinch', 'Oberkörperdruck und ein Griff hinter dem Knie kippen den Partner über die blockierte Seite.'],
  ['body-lock-trip', 'Body-Lock-Trip', 'Body lock trip', 'ボディロックトリップ', 'Bodi rokku torippu', 'Takedown', 'Clinch', 'Standing', 'Ein Griff um den Rumpf verbindet Hüftdruck mit einem inneren oder äußeren Fußhaken.'],
  ['inside-trip', 'Innerer Fußhakentakedown', 'Inside trip', '内掛', 'Uchi-gake', 'Takedown', 'Clinch', 'Standing', 'Das Bein hakt von innen, während Oberkörperkontrolle den Partner über die blockierte Seite führt.'],
  ['outside-trip', 'Äußerer Fußhakentakedown', 'Outside trip', '外掛', 'Soto-gake', 'Takedown', 'Clinch', 'Standing', 'Ein äußerer Hook blockiert das Bein und Oberkörperdruck entfernt die hintere Stütze.'],
  ['snapdown', 'Snapdown', 'Snapdown', 'スナップダウン', 'Sunappu daun', 'Takedown', 'Front Headlock Entry', 'Standing', 'Kopf und Oberkörper werden nach unten gezogen, wenn Haltung und Beine zurückweichen.'],
  ['duck-under', 'Duck-under', 'Duck-under', 'ダックアンダー', 'Dakku andā', 'Takedown', 'Back Take', 'Standing', 'Unter dem kontrollierten Arm hindurch entsteht ein Winkel hinter den Partner.'],
  ['firemans-carry', 'Feuerwehrwurf', 'Fireman’s carry', '肩車', 'Kata-guruma', 'Takedown', 'Handwurf', 'Standing', 'Schulter und Arm tragen den Schwerpunkt, während ein Bein oder Oberschenkel kontrolliert wird.'],
  ['seoi-nage', 'Schulterwurf', 'Shoulder throw', '背負投', 'Seoi-nage', 'Takedown', 'Handwurf', 'Standing', 'Der Rücken dreht unter den Schwerpunkt und die Armkontrolle führt den Partner über die Schulter.'],
  ['tai-otoshi', 'Körpersturz', 'Body drop', '体落', 'Tai-otoshi', 'Takedown', 'Handwurf', 'Standing', 'Zug und Drehung führen den Partner über ein ausgestelltes, nicht belastetes Bein.'],
  ['uchi-mata', 'Innenschenkelwurf', 'Inner-thigh throw', '内股', 'Uchi-mata', 'Takedown', 'Beinwurf', 'Standing', 'Das Bein hebt den inneren Oberschenkel, während Oberkörper und Hüfte den Partner drehen.'],
  ['harai-goshi', 'Hüftfeger', 'Sweeping hip throw', '払腰', 'Harai-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Hüfte und gestrecktes Bein fegen den belasteten Partner nach vorn-außen.'],
  ['koshi-guruma', 'Hüftrad', 'Hip wheel', '腰車', 'Koshi-guruma', 'Takedown', 'Hüftwurf', 'Standing', 'Kopf-Arm-Kontrolle und eingedrehte Hüfte erzeugen eine Radbewegung.'],
  ['sumi-gaeshi', 'Eckenkippwurf', 'Corner reversal', '隅返', 'Sumi-gaeshi', 'Takedown', 'Opferwurf', 'Standing / Guard Pull', 'Ein innerer Hook und Rückwärtsfall heben den vorwärts belasteten Partner über eine Ecke.'],
  ['tomoe-nage', 'Kreiswurf', 'Circle throw', '巴投', 'Tomoe-nage', 'Takedown', 'Opferwurf', 'Standing', 'Ein Fuß an Hüfte oder Bauch führt den Partner beim Rückwärtsfallen in einem Bogen über den Körper.'],
  ['tani-otoshi', 'Talsturz', 'Valley drop', '谷落', 'Tani-otoshi', 'Takedown', 'Seitenopferwurf', 'Standing', 'Der Körper fällt hinter die Beine des Partners und zieht ihn kontrolliert rückwärts-seitlich.'],
  ['sasae-tsurikomi-ashi', 'Hebezug-Fußstopper', 'Propping ankle throw', '支釣込足', 'Sasae-tsurikomi-ashi', 'Takedown', 'Beinwurf', 'Standing', 'Der Fuß stoppt den Knöchel, während Zug und Drehung den Oberkörper weiterführen.'],
  ['de-ashi-barai', 'Fußfeger', 'Advanced foot sweep', '出足払', 'De-ashi-barai', 'Takedown', 'Beinwurf', 'Standing', 'Der unbelastete vorwärtsschreitende Fuß wird im richtigen Moment seitlich gefegt.'],
  ['ouchi-gari', 'Große Innensichel', 'Major inner reap', '大内刈', 'Ō-uchi-gari', 'Takedown', 'Beinwurf', 'Standing', 'Das Bein sichelt ein belastetes Bein von innen, während der Oberkörper rückwärts geführt wird.'],
  ['kouchi-gari', 'Kleine Innensichel', 'Minor inner reap', '小内刈', 'Ko-uchi-gari', 'Takedown', 'Beinwurf', 'Standing', 'Der Fuß entfernt die nahe Ferse von innen, während der Schwerpunkt nach hinten sinkt.'],
  ['kosoto-gake', 'Kleiner Außenhaken', 'Minor outer hook', '小外掛', 'Ko-soto-gake', 'Takedown', 'Beinwurf', 'Standing', 'Ein äußerer Haken blockiert die Ferse, während Oberkörperkontrolle den Partner rückwärts kippt.'],
  ['kouchi-makikomi', 'Kleiner Innen-Wickelwurf', 'Minor inner wraparound', '小内巻込', 'Ko-uchi-makikomi', 'Takedown', 'Wickelwurf', 'Standing', 'Armzug und tiefer Eingang wickeln den Körper um ein inneres Bein.'],
  ['mat-return', 'Mat Return', 'Mat return', 'マットリターン', 'Matto ritān', 'Takedown', 'Wrestling', 'Rear Body Lock', 'Aus hinterem Body Lock wird der Partner angehoben oder über einen Trip kontrolliert zur Matte zurückgeführt.'],
  ['sacrifice-throw-butterfly', 'Butterfly-Opferwurf', 'Butterfly sacrifice throw', '引込返', 'Hikikomi-gaeshi', 'Takedown', 'Opferwurf', 'Standing', 'Ein Fall nach hinten verbindet Gürtel- oder Oberkörpergriff mit innerem Bein-Hook.'],

  // Klassisches Kodokan-Gokyō – ergänzt aus dem importierten Anki-Deck
  ['hiza-guruma', 'Knierad', 'Knee wheel', '膝車', 'Hiza-guruma', 'Takedown', 'Beinwurf', 'Standing', 'Der Fuß blockiert das Knie, während Zug und Körperdrehung den Partner wie über ein Rad führen.'],
  ['uki-goshi', 'Schwebende Hüfte', 'Floating hip throw', '浮腰', 'Uki-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Eine kurze Hüftanlage und Oberkörperdrehung führen den Partner über die Hüftkante.'],
  ['kosoto-gari', 'Kleine Außensichel', 'Minor outer reap', '小外刈', 'Ko-soto-gari', 'Takedown', 'Beinwurf', 'Standing', 'Die belastete Ferse wird von außen gesichelt, während der Oberkörper rückwärts geführt wird.'],
  ['tsurikomi-goshi', 'Hebezug-Hüftwurf', 'Lifting pulling hip throw', '釣込腰', 'Tsurikomi-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Hebezug und eine tiefe Hüftposition bringen den Partner über den eigenen Schwerpunkt.'],
  ['okuri-ashi-barai', 'Nachziehfußfeger', 'Sliding foot sweep', '送足払', 'Okuri-ashi-barai', 'Takedown', 'Beinwurf', 'Standing', 'Beim Seitwärtsschritt werden beide Füße zusammengeführt und in Bewegungsrichtung gefegt.'],
  ['tsuri-goshi', 'Hebehüftwurf', 'Lifting hip throw', '釣腰', 'Tsuri-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Ein Griff am Gürtel hebt den Rumpf, während die Hüfte als Drehpunkt unter den Partner gelangt.'],
  ['yoko-otoshi', 'Seitsturz', 'Side drop', '横落', 'Yoko-otoshi', 'Takedown', 'Seitenopferwurf', 'Standing', 'Der eigene Körper fällt seitlich neben den Fuß, während der Partner über die entstandene Lücke gezogen wird.'],
  ['ashi-guruma', 'Beinrad', 'Leg wheel', '足車', 'Ashi-guruma', 'Takedown', 'Beinwurf', 'Standing', 'Das gestreckte Bein bildet die Achse, über die der gedrehte Oberkörper des Partners geführt wird.'],
  ['hane-goshi', 'Sprunghüftwurf', 'Spring hip throw', '跳腰', 'Hane-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Hüfte und angewinkeltes Bein federn den vorwärts belasteten Partner diagonal nach oben.'],
  ['harai-tsurikomi-ashi', 'Hebezug-Fußfeger', 'Lifting pulling foot sweep', '払釣込足', 'Harai-tsurikomi-ashi', 'Takedown', 'Beinwurf', 'Standing', 'Hebezug bringt das Gewicht nach vorn, während der Fuß den Knöchel in Wurfrichtung fegt.'],
  ['kata-guruma', 'Schulterrad', 'Shoulder wheel', '肩車', 'Kata-guruma', 'Takedown', 'Handwurf', 'Standing', 'Der Schwerpunkt wird auf die Schultern geladen und in einer Radbewegung kontrolliert zu Boden geführt.'],
  ['hane-makikomi', 'Sprung-Wickelwurf', 'Spring wraparound throw', '跳巻込', 'Hane-makikomi', 'Takedown', 'Wickelwurf', 'Standing', 'Der Arm wird gebunden und der Körper wickelt sich beim federnden Hüfteinsatz um den Partner.'],
  ['sukui-nage', 'Schaufelwurf', 'Scoop throw', '掬投', 'Sukui-nage', 'Takedown', 'Handwurf', 'Standing', 'Der Partner wird an Hüfte oder Beinen aufgenommen und mit einer schaufelnden Bewegung ausgehoben.'],
  ['utsuri-goshi', 'Hüftwechselwurf', 'Hip shift', '移腰', 'Utsuri-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Nach dem Abfangen eines Wurfes wird der Partner angehoben und auf die andere Hüftseite umgesetzt.'],
  ['o-guruma', 'Großes Rad', 'Large wheel', '大車', 'O-guruma', 'Takedown', 'Beinwurf', 'Standing', 'Das gestreckte Bein liegt vor Hüfte oder Oberschenkeln und dient als Achse für eine große Drehbewegung.'],
  ['soto-makikomi', 'Äußerer Wickelwurf', 'Outer wraparound throw', '外巻込', 'Soto-makikomi', 'Takedown', 'Wickelwurf', 'Standing', 'Der kontrollierte Arm wird außen gebunden und der Körper eng um den Partner eingedreht.'],
  ['uki-otoshi', 'Schwebesturz', 'Floating drop', '浮落', 'Uki-otoshi', 'Takedown', 'Handwurf', 'Standing', 'Präziser Zug und ein abgesenkter Körper lenken den vorwärts schreitenden Partner in eine freie Falllinie.'],
  ['ushiro-goshi', 'Rückwärtiger Hüftwurf', 'Rear hip throw', '後腰', 'Ushiro-goshi', 'Takedown', 'Hüftwurf', 'Standing', 'Ein gegnerischer Wurf wird durch Anheben abgefangen und der Partner anschließend hinter der Hüfte abgesetzt.'],
  ['uki-waza', 'Schwebetechnik', 'Floating technique', '浮技', 'Uki-waza', 'Takedown', 'Seitenopferwurf', 'Standing', 'Seitliches Fallen und Zug führen den vorwärts belasteten Partner über das ausgestreckte Bein.'],
  ['yoko-wakare', 'Seitentrennung', 'Side separation', '横分', 'Yoko-wakare', 'Takedown', 'Seitenopferwurf', 'Standing', 'Der Körper fällt quer unter die Bewegungsrichtung und trennt die Stützlinie des Partners.'],
  ['ura-nage', 'Rückwurf', 'Rear throw', '裏投', 'Ura-nage', 'Takedown', 'Rückopferwurf', 'Standing', 'Der Partner wird eng am Rumpf angehoben und beim Rückwärtsfallen über die eigene Seite geführt.'],
  ['sumi-otoshi', 'Ecksturz', 'Corner drop', '隅落', 'Sumi-otoshi', 'Takedown', 'Handwurf', 'Standing', 'Kuzushi in eine hintere Ecke lässt den Partner ohne Beinblockade über seine Stützfläche fallen.'],
  ['yoko-gake', 'Seitlicher Haken', 'Side hook', '横掛', 'Yoko-gake', 'Takedown', 'Seitenopferwurf', 'Standing', 'Der Fuß hakt seitlich am belasteten Knöchel, während der eigene Körper kontrolliert zur Seite fällt.'],
  ['osoto-guruma', 'Großes Außenrad', 'Large outer wheel', '大外車', 'O-soto-guruma', 'Takedown', 'Beinwurf', 'Standing', 'Das Bein blockiert beide Beine von außen und der Oberkörper dreht den Partner über diese Achse.'],
  ['yoko-guruma', 'Seitenrad', 'Side wheel', '横車', 'Yoko-guruma', 'Takedown', 'Seitenopferwurf', 'Standing', 'Beim seitlichen Fall wird ein Bein tief durchgestellt, sodass der Partner radförmig darüber geführt wird.'],
];

export const CATALOG_TECHNIQUES = compact.map(expand);
