import { ImageSourcePropType } from 'react-native';

// Statische require-Aufrufe sorgen dafür, dass Metro die Bilder vollständig
// in die App bündelt. Die App benötigt dafür später keine Internetverbindung.
export const TECHNIQUE_IMAGES: Record<string, ImageSourcePropType> = {
  'de-ashi-barai': require('../assets/techniques/gokyo-no-waza2.jpg'),
  'hiza-guruma': require('../assets/techniques/gokyo-no-waza3.jpg'),
  'sasae-tsurikomi-ashi': require('../assets/techniques/gokyo-no-waza4.jpg'),
  ogoshi: require('../assets/techniques/gokyo-no-waza5.jpg'),
  'osoto-gari': require('../assets/techniques/gokyo-no-waza6.jpg'),
  'uki-goshi': require('../assets/techniques/gokyo-no-waza7.jpg'),
  'ouchi-gari': require('../assets/techniques/gokyo-no-waza8.jpg'),
  'seoi-nage': require('../assets/techniques/gokyo-no-waza9.jpg'),
  'kosoto-gari': require('../assets/techniques/gokyo-no-waza10.jpg'),
  'kouchi-gari': require('../assets/techniques/gokyo-no-waza11.jpg'),
  'koshi-guruma': require('../assets/techniques/gokyo-no-waza12.jpg'),
  'tsurikomi-goshi': require('../assets/techniques/gokyo-no-waza13.jpg'),
  'okuri-ashi-barai': require('../assets/techniques/gokyo-no-waza14.jpg'),
  'tai-otoshi': require('../assets/techniques/gokyo-no-waza15.jpg'),
  'harai-goshi': require('../assets/techniques/gokyo-no-waza16.jpg'),
  'uchi-mata': require('../assets/techniques/gokyo-no-waza17.jpg'),
  'kosoto-gake': require('../assets/techniques/gokyo-no-waza18.jpg'),
  'tsuri-goshi': require('../assets/techniques/gokyo-no-waza19.jpg'),
  'yoko-otoshi': require('../assets/techniques/gokyo-no-waza20.jpg'),
  'ashi-guruma': require('../assets/techniques/gokyo-no-waza21.jpg'),
  'hane-goshi': require('../assets/techniques/gokyo-no-waza22.jpg'),
  'harai-tsurikomi-ashi': require('../assets/techniques/gokyo-no-waza23.jpg'),
  'tomoe-nage': require('../assets/techniques/gokyo-no-waza24.jpg'),
  'kata-guruma': require('../assets/techniques/gokyo-no-waza25.jpg'),
  'firemans-carry': require('../assets/techniques/gokyo-no-waza25.jpg'),
  'sumi-gaeshi': require('../assets/techniques/gokyo-no-waza26.jpg'),
  'tani-otoshi': require('../assets/techniques/gokyo-no-waza27.jpg'),
  'hane-makikomi': require('../assets/techniques/gokyo-no-waza28.jpg'),
  'sukui-nage': require('../assets/techniques/gokyo-no-waza29.jpg'),
  'utsuri-goshi': require('../assets/techniques/gokyo-no-waza30.jpg'),
  'o-guruma': require('../assets/techniques/gokyo-no-waza31.jpg'),
  'soto-makikomi': require('../assets/techniques/gokyo-no-waza32.jpg'),
  'uki-otoshi': require('../assets/techniques/gokyo-no-waza33.jpg'),
  'osoto-guruma': require('../assets/techniques/gokyo-no-waza34.jpg'),
  'uki-waza': require('../assets/techniques/gokyo-no-waza35.jpg'),
  'yoko-wakare': require('../assets/techniques/gokyo-no-waza36.jpg'),
  'yoko-guruma': require('../assets/techniques/gokyo-no-waza37.jpg'),
  'ushiro-goshi': require('../assets/techniques/gokyo-no-waza38.jpg'),
  'ura-nage': require('../assets/techniques/gokyo-no-waza39.jpg'),
  'sumi-otoshi': require('../assets/techniques/gokyo-no-waza40.jpg'),
  'yoko-gake': require('../assets/techniques/gokyo-no-waza41.jpg'),
};