import { Technique } from './types';
import { CATALOG_TECHNIQUES } from './catalog';

const CORE_TECHNIQUES: Technique[] = [
  {
    id: 'armbar',
    names: { de: 'Gerader Armhebel', en: 'Armbar', ja: '腕挫十字固', romaji: 'Ude-hishigi-juji-gatame' },
    category: 'Submission', subcategory: 'Gelenkhebel', position: 'Guard / Mount',
    summary: 'Ein Hebel gegen das gestreckte Ellenbogengelenk. Die Hüfte bildet den Drehpunkt, während die Beine Schulter und Kopf kontrollieren.',
    steps: ['Handgelenk und Arm kontrollieren.', 'Knie eng führen und die Hüfte dicht an die Schulter bringen.', 'Daumen nach oben ausrichten, Hüfte kontrolliert anheben und den Arm strecken.'],
    keyPoints: ['Knie zusammenhalten', 'Fersen aktiv nach unten ziehen', 'Hüfte nah an der Schulter'],
    safety: 'Sehr langsam strecken und beim Tap sofort lösen. Das Ellenbogengelenk kann schnell verletzt werden.',
    sourceTitle: 'Wikipedia – Armlock', sourceUrl: 'https://en.wikipedia.org/wiki/Armlock',
  },
  {
    id: 'triangle',
    names: { de: 'Dreieckswürger', en: 'Triangle choke', ja: '三角絞', romaji: 'Sankaku-jime' },
    category: 'Submission', subcategory: 'Würgetechnik', position: 'Guard',
    summary: 'Die Beine bilden ein Dreieck um Hals und einen Arm. Druck auf beide Halsseiten schränkt die Blutzufuhr ein.',
    steps: ['Einen Arm innerhalb und einen außerhalb der Beinkontrolle halten.', 'Ein Bein über den Nacken legen und den Knöchel unter dem anderen Knie sichern.', 'Winkel verändern, Knie zusammenziehen und kontrolliert finishen.'],
    keyPoints: ['Schulter im Dreieck', 'Seitlichen Winkel herstellen', 'Nicht am eigenen Fuß ziehen'],
    safety: 'Würgetechniken nur unter Aufsicht trainieren. Bei Tap oder Bewusstseinsveränderung sofort lösen.',
    sourceTitle: 'Wikipedia – Triangle choke', sourceUrl: 'https://en.wikipedia.org/wiki/Triangle_choke',
  },
  {
    id: 'rear-naked-choke',
    names: { de: 'Würger von hinten', en: 'Rear naked choke', ja: '裸絞', romaji: 'Hadaka-jime' },
    category: 'Submission', subcategory: 'Würgetechnik', position: 'Back Control',
    summary: 'Der würgende Arm liegt um den Hals, während der zweite Arm die Position sichert. Die Technik benötigt keinen Gi-Kragen.',
    steps: ['Brust eng am Rücken halten und den würgenden Arm unter dem Kinn platzieren.', 'Hand in der gegenüberliegenden Armbeuge verstecken.', 'Mit der zweiten Hand den Hinterkopf kontrollieren und die Ellenbogen schließen.'],
    keyPoints: ['Kein Druck auf den Kehlkopf', 'Kopf dicht am Partner', 'Kontrolle vor Submission'],
    safety: 'Ohne ruckartige Bewegung anwenden und beim ersten Tap sofort lösen.',
    sourceTitle: 'Wikipedia – Rear naked choke', sourceUrl: 'https://en.wikipedia.org/wiki/Rear_naked_choke',
  },
  {
    id: 'kimura',
    names: { de: 'Kimura-Schulterhebel', en: 'Kimura lock', ja: '逆腕緘', romaji: 'Gyaku-ude-garami' },
    category: 'Submission', subcategory: 'Schulterhebel', position: 'Guard / Side Control',
    summary: 'Ein gebeugter Arm wird mit einer Vierergriff-Struktur kontrolliert und hinter den Rücken rotiert.',
    steps: ['Handgelenk kontrollieren und den eigenen Arm über den Oberarm führen.', 'Eigenes Handgelenk greifen und die Viererfigur schließen.', 'Ellenbogen am Körper halten und den Unterarm langsam hinter den Rücken führen.'],
    keyPoints: ['Handgelenk kontrollieren', 'Ellenbogen gebeugt halten', 'Mit dem Körper arbeiten'],
    safety: 'Die Schulter hat wenig Warnweg. Langsam rotieren und schon bei frühem Tap lösen.',
    sourceTitle: 'Wikipedia – Armlock', sourceUrl: 'https://en.wikipedia.org/wiki/Armlock#Keylock',
  },
  {
    id: 'americana',
    names: { de: 'Americana-Schulterhebel', en: 'Americana', ja: '腕緘', romaji: 'Ude-garami' },
    category: 'Submission', subcategory: 'Schulterhebel', position: 'Mount / Side Control',
    summary: 'Ein rechtwinklig gebeugter Arm wird am Boden fixiert und in Außenrotation belastet.',
    steps: ['Handgelenk am Boden sichern und den Ellenbogen rechtwinklig halten.', 'Unter dem Oberarm hindurch das eigene Handgelenk greifen.', 'Handrücken am Boden entlangführen und den Ellenbogen kontrolliert anheben.'],
    keyPoints: ['Handgelenk am Boden', 'Ellenbogen eng kontrollieren', 'Kleine Bewegung genügt'],
    safety: 'Keinen Schwung verwenden. Schulter und Ellenbogen sind verletzungsgefährdet.',
    sourceTitle: 'Wikipedia – Armlock', sourceUrl: 'https://en.wikipedia.org/wiki/Armlock#Keylock',
  },
  {
    id: 'guillotine',
    names: { de: 'Guillotine-Würger', en: 'Guillotine choke', ja: 'ギロチンチョーク', romaji: 'Girochin chōku' },
    category: 'Submission', subcategory: 'Würgetechnik', position: 'Standing / Guard',
    summary: 'Kopf und Hals werden von vorn mit dem Arm umschlossen. Je nach Variante wirkt der Druck auf Halsseiten oder Luftröhre.',
    steps: ['Kopfposition kontrollieren und den würgenden Arm tief führen.', 'Hände sicher verbinden und Ellenbogen eng halten.', 'Mit Körperposition und kontrolliertem Zug Druck aufbauen.'],
    keyPoints: ['Hüfte nah halten', 'Nicht nur mit den Armen ziehen', 'Handposition beachten'],
    safety: 'Besonders vorsichtig am Hals trainieren; niemals ruckartig ziehen und bei Tap sofort lösen.',
    sourceTitle: 'Wikipedia – Guillotine choke', sourceUrl: 'https://en.wikipedia.org/wiki/Guillotine_choke',
  },
  {
    id: 'osoto-gari',
    names: { de: 'Große Außensichel', en: 'Major outer reap', ja: '大外刈', romaji: 'Ō-soto-gari' },
    category: 'Takedown', subcategory: 'Beinwurf', position: 'Standing',
    summary: 'Das Gleichgewicht wird nach hinten-außen gebrochen, während ein Bein des Gegners von außen weggesichelt wird.',
    steps: ['Oberkörper kontrollieren und das Gleichgewicht auf eine hintere Ecke brechen.', 'Mit dem Standbein dicht neben den Partner treten.', 'Das andere Bein gestreckt zurückschwingen und kontrolliert durchsicheln.'],
    keyPoints: ['Brustkontakt halten', 'Standbein nah setzen', 'Zug und Sichel gleichzeitig'],
    safety: 'Nur auf Matten und mit geübtem Fallpartner trainieren. Beim Wurf Kontrolle behalten.',
    sourceTitle: 'Wikipedia – Osoto gari', sourceUrl: 'https://en.wikipedia.org/wiki/Osoto_gari',
  },
  {
    id: 'ogoshi',
    names: { de: 'Großer Hüftwurf', en: 'Full hip throw', ja: '大腰', romaji: 'Ō-goshi' },
    category: 'Takedown', subcategory: 'Hüftwurf', position: 'Standing',
    summary: 'Die Hüfte wird vor den Schwerpunkt des Gegners gebracht und dient als Drehpunkt für den Wurf.',
    steps: ['Gleichgewicht nach vorn brechen.', 'Eindrehen und die Hüfte tief vor den Partner bringen.', 'Beine strecken, Oberkörper drehen und den Partner kontrolliert über die Hüfte führen.'],
    keyPoints: ['Hüfte vollständig eindrehen', 'Knie beugen', 'Zugrichtung beibehalten'],
    safety: 'Falltechnik voraussetzen und den Partner während der Landung am Arm kontrollieren.',
    sourceTitle: 'Wikipedia – O goshi', sourceUrl: 'https://en.wikipedia.org/wiki/O_goshi',
  },
  {
    id: 'single-leg',
    names: { de: 'Einzelbeinangriff', en: 'Single-leg takedown', ja: 'シングルレッグテイクダウン', romaji: 'Shinguru reggu teikudaun' },
    category: 'Takedown', subcategory: 'Beinangriff', position: 'Standing',
    summary: 'Ein Bein wird kontrolliert, um Stand und Gleichgewicht zu beseitigen und den Kampf zu Boden zu bringen.',
    steps: ['Distanz schließen und die Ebene mit geradem Rücken wechseln.', 'Bein eng umfassen und Kopf stabil am Oberkörper positionieren.', 'Aufstehen, Winkel herstellen und kontrolliert zu Boden führen.'],
    keyPoints: ['Kopf auf der sicheren Seite', 'Rücken stabil', 'Bein dicht am Körper'],
    safety: 'Nicht seitlich gegen das Knie fallen. Takedown kontrolliert abschließen.',
    sourceTitle: 'Wikipedia – Takedown', sourceUrl: 'https://en.wikipedia.org/wiki/Takedown_(grappling)',
  },
  {
    id: 'scissor-sweep',
    names: { de: 'Scherensweep', en: 'Scissor sweep', ja: 'シザースイープ', romaji: 'Shizā suīpu' },
    category: 'Sweep', subcategory: 'Guard Sweep', position: 'Closed Guard',
    summary: 'Eine scherenartige Beinbewegung kippt den Gegner aus der Guard und ermöglicht den Wechsel in die obere Position.',
    steps: ['Griff und Arm kontrollieren.', 'Auf die Seite drehen und ein Knie als Rahmen vor die Brust bringen.', 'Mit oberem Bein schieben, unterem Bein fegen und den Oberkörper führen.'],
    keyPoints: ['Seitlichen Winkel schaffen', 'Balance zuerst brechen', 'Arm der Fallseite kontrollieren'],
    safety: 'Das untere Bein flach führen und nicht seitlich gegen das Knie des Partners treten.',
    sourceTitle: 'Wikipedia – Sweep', sourceUrl: 'https://en.wikipedia.org/wiki/Sweep_(martial_arts)',
  },
  {
    id: 'shrimp',
    names: { de: 'Hüftflucht', en: 'Shrimp escape', ja: '海老', romaji: 'Ebi' },
    category: 'Escape', subcategory: 'Grundbewegung', position: 'Bottom Position',
    summary: 'Die Hüfte bewegt sich vom Gegner weg, um Raum für Rahmen, Knie oder eine Guard-Recovery zu schaffen.',
    steps: ['Seitlich drehen und mit Armen stabile Rahmen bilden.', 'Außenfuß aufstellen und die Hüfte diagonal nach hinten schieben.', 'Knie in den Raum bringen und Position wiederherstellen.'],
    keyPoints: ['Auf der Seite bleiben', 'Mit dem Fuß drücken', 'Rahmen offen halten'],
    safety: 'Nicht mit ausgestreckten Armen drücken. Ellenbogen eng und Schulter geschützt halten.',
    sourceTitle: 'Wikipedia – Shrimping', sourceUrl: 'https://en.wikipedia.org/wiki/Shrimping_(martial_arts)',
  },
  {
    id: 'upa-escape',
    names: { de: 'Brücken-und-Roll-Befreiung', en: 'Bridge-and-roll escape', ja: 'ウパ・エスケープ', romaji: 'Upa esukēpu' },
    category: 'Escape', subcategory: 'Mount Escape', position: 'Bottom Mount',
    summary: 'Arm und Fuß einer Seite werden blockiert; eine kräftige Brücke kippt den Gegner über diese fehlende Stützseite.',
    steps: ['Arm und gleichseitigen Fuß kontrollieren.', 'Fersen nah ans Gesäß bringen und zuerst gerade hoch brücken.', 'Zur blockierten Seite drehen und in die obere Position folgen.'],
    keyPoints: ['Arm und Fuß einer Seite', 'Erst hoch, dann rollen', 'Kopf aktiv halten'],
    safety: 'Finger nicht einzeln greifen. Partner kontrolliert rollen lassen und den Nacken nicht überstrecken.',
    sourceTitle: 'Wikipedia – Mount', sourceUrl: 'https://en.wikipedia.org/wiki/Mount_(grappling)',
  },
];

export const TECHNIQUES: Technique[] = [...CORE_TECHNIQUES, ...CATALOG_TECHNIQUES];
export const CATEGORIES = ['Alle', ...Array.from(new Set(TECHNIQUES.map((technique) => technique.category)))];
